apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.34.0 (cbf2835db)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.34.0 (cbf2835db)
      labels:
        io.kompose.service: frontend
    spec:
      containers:
        - env:
            - name: VITE_API_PATH
              valueFrom:
                configMapKeyRef:
                  key: VITE_API_PATH
                  name: frontend-env-docker
          image: sarvagyamishra82/3-tier-frontend:latest
          name: frontend
          ports:
            - containerPort: 5173
              protocol: TCP
      restartPolicy: Always
